---
configure_explorer: true
configure_start_menu: true
configure_taskbar: true
disable_mouse_acceleration: true
ohmyposh_theme: craver
remove_desktop_icons: true
remote_desktop_enabled: true
set_sound_scheme: true

install_windows_updates: false
windows_updates_reboot: true
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  # - "*"
  - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  - Security Updates
  # - Service Packs
  # - Tools
  - Update Rollups
  # - Updates
  # - Upgrades

change_power_plan: true
# high_performance
# balanced
# power_saver
power_plan: "high_performance"

install_scoop_packages: true
scoop_packages:
  - 7zip
  - aws
  - curl
  - discord
  - dagger
  - git
  - gpg
  - jq
  - kubectl
  - openlens
  - postman
  - rancher-desktop
  - windows-terminal

install_winget_packages: true
winget_packages:
  # - name: "Auto Dark Mode"
  #   source: winget
  - name: WinDynamicDesktop
    source: winget
  - name: Microsoft.PowerShell
    source: winget

install_fonts: true
installed_nerdfonts:
  - FiraCode
  - FantasqueSansMono

install_ohmyposh: true

# List of features: "Get-WindowsOptionalFeature -Online"
install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true

remove_bloatware: true
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  # - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  # # - Microsoft.MSPaint
  # - Microsoft.Office.OneNote
  # - Microsoft.OneConnect
  # - Microsoft.People
  # - Microsoft.PowerAutomateDesktop
  # - Microsoft.Print3D
  # - Microsoft.ScreenSketch
  # - Microsoft.SkypeApp
  # - Microsoft.Todos
  # - Microsoft.Windows.Photos
  # - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  # - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  # - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams

defrag_volumes: true
include_volumes:
  - C
