---
collections:
  - name: ansible.utils
    version: 2.9.0
  - name: ansible.posix
    version: 1.4.0
  - name: ansible.windows
    version: 1.13.0
  - name: community.general
    version: 5.8.8
  - name: community.windows
    version: 1.12.0
  - name: chocolatey.chocolatey
    version: 1.4.0
