---

- name: MailUp environment playbook.
  hosts: windows
  vars_files:
    - default.config.yml
    - secrets.config.yml
  tasks:
    - name: Test connection
      ansible.windows.win_ping:

    - name: Include debloat configuration.
      ansible.builtin.import_tasks:
        file: tasks/debloat.yml
      when: remove_bloatware
      tags: ["debloat"]

    - name: Include windows updates configuration.
      ansible.builtin.import_tasks:
        file: tasks/updates.yml
      when: install_windows_updates
      tags: ["updates"]

    - name: Include scoop configuration.
      ansible.builtin.import_tasks:
        file: tasks/scoop.yml
      when: install_scoop_packages
      tags: ["scoop"]

    - name: Include winget configuration.
      ansible.builtin.import_tasks:
        file: tasks/winget.yml
      when: install_winget_packages
      tags: ["winget"]

    - name: Include fonts configuration.
      ansible.builtin.import_tasks:
        file: tasks/fonts.yml
      when: install_fonts
      tags: ["fonts"]

    - name: Include ohmyposh configuration.
      ansible.builtin.import_tasks:
        file: tasks/ohmyposh.yml
      when: install_ohmyposh
      tags: ["ohmyposh"]

    - name: Include explorer configuration.
      ansible.builtin.import_tasks:
        file: tasks/explorer.yml
      when: configure_explorer
      tags: ["explorer"]

    - name: Include taskbar conf
      ansible.builtin.import_tasks:
        file: tasks/taskbar.yml
      when: configure_taskbar
      tags: ["taskbar"]

    - name: Include start menu configuration.
      ansible.builtin.import_tasks:
        file: tasks/start_menu.yml
      when: configure_start_menu
      tags: ["start_menu"]

    - name: Include sounds configuration.
      ansible.builtin.import_tasks:
        file: tasks/sounds.yml
      when: set_sound_scheme
      tags: ["sounds"]

    - name: Include mouse configuration.
      ansible.builtin.import_tasks:
        file: tasks/mouse.yml
      when: disable_mouse_acceleration
      tags: ["mouse"]

    - name: Include power plan configuration.
      ansible.builtin.import_tasks:
        file: tasks/power_plan.yml
      when: change_power_plan
      tags: ["power"]

    - name: Include remote desktop configuration.
      ansible.builtin.import_tasks:
        file: tasks/remote_desktop.yml
      when: remote_desktop_enabled
      tags: ["remote_desktop"]

    - name: Include desktop configuration.
      ansible.builtin.import_tasks:
        file: tasks/desktop.yml
      when: remove_desktop_icons
      tags: ["desktop"]

    - name: Include storage sense configuration.
      ansible.builtin.import_tasks:
        file: tasks/storage.yml
      when: configure_storage_sense
      tags: ["storage_sense"]
